# Generated by Django 5.2.4 on 2025-11-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='filial',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lastname_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='second_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='staff',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Должность'),
        ),
    ]
