# Generated by Django 5.2.4 on 2025-11-19 23:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-last_message_at'], 'verbose_name': 'Беседа', 'verbose_name_plural': 'Беседы'},
        ),
        migrations.AlterModelOptions(
            name='conversationmember',
            options={'verbose_name': 'Участник беседы', 'verbose_name_plural': 'Участники бесед'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sent_at'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='messageattachment',
            options={'verbose_name': 'Вложение сообщения', 'verbose_name_plural': 'Вложения сообщений'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='conversation_avatars/', verbose_name='Аватар беседы'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_message_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее сообщение'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('private', 'Личная'), ('group', 'Групповая')], default='private', max_length=10, verbose_name='Тип беседы'),
        ),
        migrations.AlterField(
            model_name='conversationmember',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.conversation', verbose_name='Беседа'),
        ),
        migrations.AlterField(
            model_name='conversationmember',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата присоединения'),
        ),
        migrations.AlterField(
            model_name='conversationmember',
            name='role',
            field=models.CharField(choices=[('member', 'Участник'), ('admin', 'Администратор')], default='member', max_length=10, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='conversationmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversation', verbose_name='Беседа'),
        ),
        migrations.AlterField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата редактирования'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Отредактировано'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(upload_to='message_attachments/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='file_name',
            field=models.CharField(max_length=255, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='file_size',
            field=models.BigIntegerField(verbose_name='Размер файла'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='mime_type',
            field=models.CharField(max_length=100, verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Был в сети'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='В сети', max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='users_profiles',
        ),
    ]
