# Generated by Django 5.2.4 on 2025-11-20 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_filial_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='lastname_name',
            new_name='last_name',
        ),
    ]
