# Generated by Django 5.2.4 on 2025-11-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_lastname_name_userprofile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Почта'),
        ),
    ]
