# Generated by Django 5.2.4 on 2025-12-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='is_stored_in_minio',
            field=models.BooleanField(default=True, help_text='Файл хранится в MinIO (True) или локально (False)', verbose_name='Хранится в MinIO'),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='storage_path',
            field=models.CharField(blank=True, help_text='Полный путь к файлу в MinIO', max_length=500, verbose_name='Путь в хранилище'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(upload_to='message_attachments/%Y/%m/%d/', verbose_name='Файл'),
        ),
    ]
