# Generated by Django 5.2.4 on 2025-12-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_messageattachment_is_stored_in_minio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(upload_to='message_attachments/Год %Y/Месяц %m/День %d/', verbose_name='Файл'),
        ),
    ]
